# PR workflow.
#
# Runs full suite of checks, with warnings treated as errors.

name: Node Changes

on: pull_request
   
    
env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  TEST_STARTUP_INTERVAL: "40"

jobs:
 
  node-tests:
    if: |
      github.repository_owner == 'maidsafe' &&
      !startsWith(github.event.pull_request.title, 'Automated version bump')
    name: Node Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      # test for changes. (dont use baked in GHA pr/paths filter as then job wont run and we can't require itz)
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/node/**'
              - 'src/routing/**'
              - 'src/messaging/**'
              - 'src/types/**'

      # Install Rust
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.src == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        if: steps.changes.outputs.src == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      # Run tests.
      # Currently do not run client tests on mac
      - name: Cargo tests
        if: steps.changes.outputs.src == 'true'
        run: cargo test --release node

      - name: Configuration test
        if: steps.changes.outputs.src == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --example config_handling -- --first 127.0.0.1:0 -h ${{ '["127.0.0.1:1234"]' }}

      - name: Upload node data on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: nodes-data
          path: nodes

